name: Deploy to GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: [main]
=======
    branches: [master]
>>>>>>> 794ef74246f92f369f218ade8bd6a833e5d463ab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
<<<<<<< HEAD
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
=======
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
>>>>>>> 794ef74246f92f369f218ade8bd6a833e5d463ab
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
